-- AlterTable
ALTER TABLE "MaterialGF" ADD COLUMN     "montaje" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tablaEtq" TEXT NOT NULL DEFAULT '';


-- Materiales de etiqueta (por lámina de montaje), del catálogo Digital Print. Idempotente.
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-estandar', 'Etiqueta Vinil Estándar 140gr', 'Etiqueta', 12, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-estandar-lam', 'Etiqueta Vinil Estándar laminado', 'Etiqueta', 16, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-matte', 'Etiqueta Vinil Matte / Blackout', 'Etiqueta', 13, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-matte-lam', 'Etiqueta Vinil Matte / Blackout laminado', 'Etiqueta', 17, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-clear', 'Etiqueta Vinil Clear Brillante', 'Etiqueta', 13, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-clear-lam', 'Etiqueta Vinil Clear laminado', 'Etiqueta', 17, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-vinil', 'Etiqueta UV Vinil (sin reserva)', 'Etiqueta UV', 22, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-vinil-cr', 'Etiqueta UV Vinil (con reserva)', 'Etiqueta UV', 28, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-clear', 'Etiqueta UV Clear (sin reserva)', 'Etiqueta UV', 22, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-clear-cr', 'Etiqueta UV Clear (con reserva)', 'Etiqueta UV', 28, 'etiqueta', '', '125x70', '3x3:660,4x4:510,5x5:310,6x6:220,7x7:170', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-holo', 'Etiqueta UV Holográfico (sin reserva)', 'Etiqueta UV', 26, 'etiqueta', '', '115x70', '3x3:600,4x4:450,5x5:280,6x6:190,7x7:160', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-holo-cr', 'Etiqueta UV Holográfico (con reserva)', 'Etiqueta UV', 34, 'etiqueta', '', '115x70', '3x3:600,4x4:450,5x5:280,6x6:190,7x7:160', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-dorado', 'Etiqueta UV Dorado / Rose Gold (sin reserva)', 'Etiqueta UV', 14, 'etiqueta', '', '50x90', '4x4:252,5x5:153,6x6:112,7x7:84', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","montaje","tablaEtq","activo") VALUES (gen_random_uuid()::text, 'gf-etq-uv-dorado-cr', 'Etiqueta UV Dorado / Rose Gold (con reserva)', 'Etiqueta UV', 17, 'etiqueta', '', '50x90', '4x4:252,5x5:153,6x6:112,7x7:84', true) ON CONFLICT ("clave") DO NOTHING;
