-- AlterTable
ALTER TABLE "Config" ALTER COLUMN "gfOjeteCosto" SET DEFAULT 0.8;


-- Ojete al precio del proveedor (Digital Print: $0,8 instalado, incluye refilado).
-- Corrige el ajuste previo a $0,2; solo pisa si sigue en un placeholder.
UPDATE "Config" SET "gfOjeteCosto" = 0.8 WHERE "gfOjeteCosto" IN (0.2, 0.5);

-- Materiales de gran formato (catálogo Digital Print completo). Idempotente.
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-13oz', 'Banner 13 oz', 'Banner', 7, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-reciclaje', 'Banner Reciclaje', 'Banner', 6, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-backlight', 'Banner Backlight', 'Banner', 8, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-blackout', 'Banner Blackout', 'Banner', 8, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-mesh', 'Banner Mesh', 'Banner', 10, 'mancha', '320', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-13oz-lam', 'Banner 13 oz laminado', 'Banner laminado', 14, 'mancha', '137,152', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-blackout-lam', 'Banner Blackout laminado', 'Banner laminado', 15, 'mancha', '137,152', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-estandar', 'Vinil Estándar 140gr', 'Vinil', 7, 'ancho_rollo', '105,137,152', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-blackout', 'Vinil Blackout', 'Vinil', 8, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-matte', 'Vinil Matte', 'Vinil', 8, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-clear', 'Clear Brillante', 'Vinil', 8, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-microperforado', 'Vinil Microperforado', 'Vinil', 11, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-holografico', 'Vinil Holográfico', 'Vinil', 13, 'ancho_rollo', '127', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-140-lam', 'Vinil 140gr laminado', 'Vinil laminado', 14, 'ancho_rollo', '137,152', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-blackout-lam', 'Vinil Blackout laminado', 'Vinil laminado', 14, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-13oz-uv', 'Banner 13 oz UV', 'Banner UV', 15, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-13oz-uv-sr', 'Banner 13 oz UV Premium (sin reserva)', 'Banner UV', 22, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-13oz-uv-cr', 'Banner 13 oz UV Premium (con reserva)', 'Banner UV', 26, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-blackout-uv', 'Banner Blackout UV', 'Banner UV', 16, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-blackout-uv-sr', 'Banner Blackout UV Premium (sin reserva)', 'Banner UV', 23, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-blackout-uv-cr', 'Banner Blackout UV Premium (con reserva)', 'Banner UV', 30, 'mancha', '', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-backlight-uv', 'Banner Backlight UV', 'Banner UV', 18, 'mancha', '90,115,140,160,180', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-backlight-uv-sr', 'Banner Backlight UV Premium (sin reserva)', 'Banner UV', 24, 'mancha', '90,115,140,160,180', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-banner-backlight-uv-cr', 'Banner Backlight UV Premium (con reserva)', 'Banner UV', 32, 'mancha', '90,115,140,160,180', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-estandar-uv', 'Vinil Estándar UV (sin reserva)', 'Vinil UV', 18, 'ancho_rollo', '137,152', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-estandar-uv-cr', 'Vinil Estándar UV (con reserva)', 'Vinil UV', 24, 'ancho_rollo', '137,152', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-matte-uv', 'Vinil Matte UV (sin reserva)', 'Vinil UV', 18, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-vinil-matte-uv-cr', 'Vinil Matte UV (con reserva)', 'Vinil UV', 24, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-clear-uv', 'Clear UV (sin reserva)', 'Vinil UV', 18, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-clear-uv-cr', 'Clear UV (con reserva)', 'Vinil UV', 24, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-microperforado-uv', 'Vinil Microperforado UV (sin reserva)', 'Vinil UV', 22, 'ancho_rollo', '137', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-holografico-uv', 'Vinil Holográfico UV (sin reserva)', 'Vinil UV', 22, 'ancho_rollo', '127', true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "MaterialGF" ("id","clave","nombre","categoria","costoM2","modoCobro","anchosRollo","activo") VALUES (gen_random_uuid()::text, 'gf-holografico-uv-cr', 'Vinil Holográfico UV (con reserva)', 'Vinil UV', 30, 'ancho_rollo', '127', true) ON CONFLICT ("clave") DO NOTHING;

-- Productos terminados de gran formato.
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-pendon-40x60', 'Pendón 40×60', 'Pendón', '40×60 cm', 5, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-pendon-60x90', 'Pendón 60×90', 'Pendón', '60×90 cm', 8.5, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-pendon-80x120', 'Pendón 80×120', 'Pendón', '80×120 cm', 12, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-pendon-100x140', 'Pendón 100×140', 'Pendón', '100×140 cm', 16, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-rollup-85x200', 'Roll Up estructura 85×200', 'Roll Up', '85×200 cm', 45, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-rollup-blackout-85x200', 'Roll Up + Banner Blackout 85×200', 'Roll Up', '85×200 cm', 65, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-arana-13oz-60x160', 'Araña + Banner 13oz 60×160', 'Araña', '60×160 cm', 30, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-arana-13oz-80x170', 'Araña + Banner 13oz 80×170', 'Araña', '80×170 cm', 35, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-arana-uv-60x160', 'Araña + Banner 13oz UV 60×160', 'Araña', '60×160 cm', 35, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-arana-uv-80x170', 'Araña + Banner 13oz UV 80×170', 'Araña', '80×170 cm', 45, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-porta-arana-60x160', 'Porta pendón Araña 60×160', 'Estructura', '60×160 cm', 20, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-porta-arana-80x170', 'Porta pendón Araña 80×170', 'Estructura', '80×170 cm', 24, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-porta-doble-cara', 'Porta pendón doble cara', 'Estructura', 'hasta 180 cm', 25, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-stand-degustacion', 'Stand de degustación (sin rotular)', 'Stand', '80×196 cm', 100, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-stand-degustacion-rot', 'Stand de degustación (rotulado)', 'Stand', '80×196 cm', 156, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-bolsillo-peq', 'Bolsillo y refilado (par, hasta 50 cm)', 'Accesorio', 'hasta 50 cm', 1.5, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-bolsillo-med', 'Bolsillo y refilado (par, hasta 1 m)', 'Accesorio', 'hasta 1 m', 2.5, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-tubo-peq', 'Tubo + cuerda + regetones (30–60 cm)', 'Accesorio', '30–60 cm', 3.5, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-tubo-med', 'Tubo + cuerda + regetones (70–120 cm)', 'Accesorio', '70–120 cm', 5, true) ON CONFLICT ("clave") DO NOTHING;
INSERT INTO "ProductoGF" ("id","clave","nombre","categoria","medida","costoUnit","activo") VALUES (gen_random_uuid()::text, 'gf-tubo-gra', 'Tubo + cuerda + regetones (121–150 cm)', 'Accesorio', '121–150 cm', 6, true) ON CONFLICT ("clave") DO NOTHING;
